exclude:
  public
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml  # 检查yaml文件
      - id: end-of-file-fixer # 文本文件是否以换行符结束
      - id: check-merge-conflict # 是否存在合并冲突
      - id: mixed-line-ending # 检查结束符，使用Unix LF
      - id: trailing-whitespace # 取消行尾无关紧要的空格
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.10.0
    hooks:
      - id: commitizen
        stages: [ commit-msg ]
